version: "3.8"

networks:
  base-network:
    driver: bridge
    name: mult-network
  # ipfs-network:
  #   driver: bridge
  #   name: ipfs-network

volumes:
  ctx:
    driver: local
    driver_opts:
      type: none
      device: ../../
      # device: $PWD/${WEB_APP_PATH}
      o: bind

services:

  mult:
    image: mult.mult
    build:
      context: ./mult
      dockerfile: ./Dockerfile
      args:
        workdir: /ctx/mult/bin/mult
    command: tail -f /dev/null
    # command: bash f dev
    # expose:
    #   - 7788
    ports:
      - 8000:8000
      - 8001:8001
      - 9500:9500
      - 8899:8899
      - 9630:9630
    environment:
      - SHADOWCLJS_DEVTOOLS_URL=http://localhost:9630
    networks:
      - base-network
    # user: 1000:1000
    volumes:
      - ./mult/.user:/root
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M