#!/bin/bash

purge(){
    rm -rf .shadow-cljs node_modules .cpcache 
}

clean(){
    rm -rf resources/out
}

shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

server(){
    shadow -A:core:dev server
    # yarn server
}

dev(){
    npm i
    shadow -A:core:dev watch :extension :tabapp
}

compile(){
    npm i
    shadow -A:core:dev compile :extension :tabapp
}

dock() {

    docker build -t mult -f Dockerfile .
    docker run  --rm \
                --cpus=4.0 \
                --memory=4g \
                --name mult \
                -it \
                -p 5100:5100 \
                -p 5101:5101 \
                -p 5102:5102 \
                -v "$(pwd)":/ctx/app \
                 mult \
                 bash
}


"$@"