version: "3.7"

services:

  mango:
    image: fruits.mango
    volumes:
      - ./system:/ctx/system
      - ./containers/mango:/ctx/app
    build:
      context: ./
      dockerfile: ./containers/mango/Dockerfile
    ports:
      - 7788:7788
    command: bash f dev
    # command: tail -f /dev/null
    environment:
      - DISPLAY
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  banana:
    image: fruits.banana
    volumes:
      - ./system:/ctx/system
      - ./containers/banana:/ctx/app
    build:
      context: ./
      dockerfile: ./containers/banana/Dockerfile
    ports:
      - 8899:8899
      - 9630:9630
      - 9000:9500
    command: bash f dev
    # command: tail -f /dev/null
    environment:
      - DISPLAY
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        