#!/bin/bash

clean(){
    rm -rf .shadow-cljs node_modules .cpcache resources/public/js-out
}

shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

server(){
    shadow -A:core server
    # yarn server
}

test(){
    npm i
    shadow -A:core:dev:local watch test
}

dev(){
    npm i
    shadow -A:core:dev:local watch :app
    # npx shadow-cljs -A:dev:local watch app
    # yarn dev
}

release(){
    npm i
    shadow -A:core:optimized:local release app
}

"$@"